project:
  type: website
  output-dir: docs

website:
  title: "Poruri Sai Rahul"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - talks.qmd
    tools:
      - icon: mastodon
        href: https://mastodon.social/@rahulporuri
      - icon: linkedin
        href: https://www.linkedin.com/in/rahulporuri
      - icon: telegram
        href: https://t.me/rahulporuri
      - icon: github
        href: https://github.com/rahulporuri
  page-footer:
    left: "Copyright 2025, Poruri Sai Rahul. Built with [Quarto](https://quarto.org/)"
    border: true
    center:
      - icon: envelope-at
        href: mailto:rahul@fossunited.org
      - icon: envelope-at-fill
        href: mailto:rahul.poruri@gmail.com
      - icon: journal-bookmark-fill
        href: https://rahulporuri.blogspot.com
      - icon: map-fill
        href: https://www.openstreetmap.org/user/rahulporuri
      - icon: journal-bookmark
        href: https://rahulandluffyread.blogspot.com/
      - icon: instagram
        href: https://www.instagram.com/rahulporuri/
      - icon: youtube
        href: https://www.youtube.com/@rahulporuri
      - icon: discord
        href: https://discord.com/users/rahulporuri
      - icon: reddit
        href: https://www.reddit.com/user/rahul_poruri/
      - icon: git
        href: https://codeberg.org/rahulporuri
      - icon: book-half
        href: https://app.thestorygraph.com/profile/rahulporuri

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
